In [ ]:
import pandas as pd # data manipulation, preprocessing

In [ ]:
file_path = "/content/homicideinenglandandwalesappendixtablesyemar2024.xlsx"  # creating a var instead of directly loading it so it can be loaded with a specific table

In [ ]:
df = pd.read_excel(file_path, sheet_name='Table 1', skiprows=7) # sheet selection and skipping the top few rows ie filtering them out

/usr/local/lib/python3.11/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Worksheet 16'!$A:$N.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

In [ ]:
df.head(10) # sampling the data to make sure its been ingested and filtered accordingly

,Year,Number of offences initially recorded as homicide,Number of offences\nno longer recorded\nas homicide,Number of offences currently recorded as homicide,Offences currently recorded as homicide rate per million population [note 5]
0,Jan 1960 to Dec 1960,282,[x],[x],[x]
1,Jan 1961 to Dec 1961,265,[x],[x],[x]
2,Jan 1962 to Dec 1962,299,[x],[x],[x]
3,Jan 1963 to Dec 1963,307,[x],[x],[x]
4,Jan 1964 to Dec 1964,296,[x],[x],[x]
5,Jan 1965 to Dec 1965,325,[x],[x],[x]
6,Jan 1966 to Dec 1966,364,[x],[x],[x]
7,Jan 1967 to Dec 1967,414,60,354,7.3
8,Jan 1968 to Dec 1968,420,60,360,7.4
9,Jan 1969 to Dec 1969,395,63,332,6.8

In [ ]:
df.replace('[x]', pd.NA, inplace=True) # the [x] boxes are better being converted to just NA so theres no error

In [ ]:
df.head() # sampling to see if the change has been made

,Year,Number of offences initially recorded as homicide,Number of offences\nno longer recorded\nas homicide,Number of offences currently recorded as homicide,Offences currently recorded as homicide rate per million population [note 5]
0,Jan 1960 to Dec 1960,282,<NA>,<NA>,<NA>
1,Jan 1961 to Dec 1961,265,<NA>,<NA>,<NA>
2,Jan 1962 to Dec 1962,299,<NA>,<NA>,<NA>
3,Jan 1963 to Dec 1963,307,<NA>,<NA>,<NA>
4,Jan 1964 to Dec 1964,296,<NA>,<NA>,<NA>

In [ ]:
# TABLES NEEDED FOR ANALYSIS

# TABLE 20 UNDER INFLUENCE                                 DONE
# TABLE 22 DRUG RELATED DEALER ETC                         DONE
# TABLE 9 KNIFE CRIME AND TYPE OF KNIFE                    DONE
# TABLE 10 CRIME WITH TEENAGERS                            DONE
# TABLE 11 KNIFE CRIME 2014 TO 2024                        DONE
# TABLE 13 FIREARM CRIME                                   DONE
# TABLE 15 CRIME 16 AND OVER                               DONE
# TABLE 16 CRIME 16 AND UNDER                              DONE

In [ ]:
df_knifecrime_typeknife = pd.read_excel(file_path, sheet_name='Table 9', skiprows=6) # repeating same code but for another table with rows skipped based on the redundant rows in the flatfile

/usr/local/lib/python3.11/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Worksheet 16'!$A:$N.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

In [ ]:
df_teen_crime = pd.read_excel(file_path, sheet_name='Table 10', skiprows=6) # skiprows make sure the redundant data isnt there

/usr/local/lib/python3.11/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Worksheet 16'!$A:$N.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

In [ ]:
df_knife_crime2014_to24 = pd.read_excel(file_path, sheet_name='Table 11', skiprows=6)

/usr/local/lib/python3.11/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Worksheet 16'!$A:$N.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

In [ ]:
df_firearm_crime = pd.read_excel(file_path, sheet_name='Table 13', skiprows=6)

/usr/local/lib/python3.11/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Worksheet 16'!$A:$N.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

In [ ]:
table15a = pd.read_excel(file_path, sheet_name='Worksheet 15', skiprows=8, nrows=40) # using n rows to capture the right cells needed since a and b are stacked
table15b = pd.read_excel(file_path, sheet_name='Worksheet 15', skiprows=50, nrows=40)

# merging here is needed because 15a is the count and 15b is the percetnage so the tables should be joined using inner to retain all information as default
crime_age16_over = table15a.merge(
    table15b,
    on=['Sex of victim', 'Victim acquainted with suspect', 'Relationship to principal suspect'], how='inner',suffixes=('_count', '_percent'))

/usr/local/lib/python3.11/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Worksheet 16'!$A:$N.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")
/usr/local/lib/python3.11/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Worksheet 16'!$A:$N.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

In [ ]:
table16a = pd.read_excel(file_path, sheet_name='Worksheet 16', skiprows=8, nrows=34) # using n rows to capture the right cells needed since a and b are stacked
table16b = pd.read_excel(file_path, sheet_name='Worksheet 16', skiprows=35, nrows=24)

# merging here is needed as before
crime_age16_under = table16a.merge(
    table16b,
    on=['Sex of victim', 'Victim acquainted with suspect', 'Relationship to principal suspect'], how='inner',suffixes=('_count', '_percent'))

/usr/local/lib/python3.11/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Worksheet 16'!$A:$N.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")
/usr/local/lib/python3.11/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Worksheet 16'!$A:$N.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

In [ ]:
crime_underinfluence = pd.read_excel(file_path, sheet_name='Table 20', skiprows=6)

/usr/local/lib/python3.11/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Worksheet 16'!$A:$N.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

In [ ]:
drug_crime_related = pd.read_excel(file_path, sheet_name='Table 22', skiprows=6)

/usr/local/lib/python3.11/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: 'Worksheet 16'!$A:$N.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

In [ ]:
crime_age16_under.head() # displaying a sample for the selected table to make sure theyre all correctly processed

,Sex of victim,Victim acquainted with suspect,Relationship to principal suspect,Apr 2013 to Mar 2014_count,Apr 2014 to Mar 2015\n[note 17]_count,Apr 2015 to Mar 2016_count,Apr 2016 to Mar 2017_count,Apr 2017 to Mar 2018_count,Apr 2018 to Mar 2019\n[note 17]_count,Apr 2019 to Mar 2020_count,...,Apr 2014 to Mar 2015\n[note 17]_percent,Apr 2015 to Mar 2016_percent,Apr 2016 to Mar 2017_percent,Apr 2017 to Mar 2018_percent,Apr 2018 to Mar 2019\n[note 17]_percent,Apr 2019 to Mar 2020_percent,Apr 2020 to Mar 2021\n[note 17]_percent,Apr 2021 to Mar 2022_percent,Apr 2022 to Mar 2023_percent,Apr 2023 to Mar 2024_percent
0,Male,Victim acquainted with suspect,Son or daughter,10,21,7,22,16,12,13,...,67.741935,43.75,50,59.259259,36.363636,38.235294,58.823529,41.463415,46.666667,38.461538
1,Male,Victim acquainted with suspect,Other family/friend/acquaintance,2,3,1,5,4,10,5,...,9.677419,6.25,11.363636,14.814815,30.30303,14.705882,14.705882,19.512195,16.666667,3.846154
2,Male,Victim acquainted with suspect,Total,12,24,8,27,20,22,18,...,77.419355,50,61.363636,74.074074,66.666667,52.941176,73.529412,60.97561,63.333333,42.307692
3,Male,Victim not known to be acquainted with suspect,Stranger,2,1,0,0,0,4,5,...,3.225806,[x],[x],[x],12.121212,14.705882,2.941176,4.878049,6.666667,7.692308
4,Male,Victim not known to be acquainted with suspect,Relationship not known,0,0,1,0,2,1,1,...,[x],6.25,[x],7.407407,3.030303,2.941176,2.941176,7.317073,[x],7.692308

In [ ]:
# saving the datasets now as seperate csv files to be implemented to streamlit
crime_age16_over.to_csv(r'/content/Crime_Aged 16+.csv', index=False)
df_knifecrime_typeknife.to_csv(r'/content/Knife crime with type of knife reported.csv', index=False)
df_teen_crime.to_csv(r'/content/Crime involving Teenagers.csv', index=False)
df_knife_crime2014_to24.to_csv(r'/content/Knife crime 2014 - 2024.csv', index=False)
df_firearm_crime.to_csv(r'/content/Crime involving Firearm.csv', index=False)
crime_age16_under.to_csv(r'/content/Crime_Aged under 16.csv', index=False)
crime_underinfluence.to_csv(r'/content/Crime under influence.csv', index=False)
drug_crime_related.to_csv(r'/content/Drug Related Crime.csv', index=False)